# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  android: circleci/android@0.2.3

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: Build Project
          command: ./gradlew assemble
